zabbix_export:
  version: '5.4'
  date: '2022-01-04T09:47:33Z'
  groups:
    -
      uuid: 7df96b18c230490a9a0a9e2307226338
      name: Templates
  templates:
    -
      uuid: ad617ee2206f4c24a0dbdd93a1e2bbcf
      template: 'Microsoft Windows Application auditing'
      name: 'Microsoft Windows Application auditing'
      groups:
        -
          name: Templates
      items:
        -
          uuid: 0e7f55a28b4b4784bcfa6855cfa5c2e9
          name: 'Event ID - 11707'
          type: ZABBIX_ACTIVE
          key: 'eventlog[Application,,,,11707,,skip]'
          delay: 10s
          history: 30d
          trends: '0'
          value_type: LOG
          tags:
            -
              tag: Windows
              value: 'Event ID alert'
          triggers:
            -
              uuid: dc8fd5fc20ae4e718dc1dd50b5b4b123
              expression: 'logeventid(/Microsoft Windows Application auditing/eventlog[Application,,,,11707,,skip])=1'
              name: 'Event ID11707_Product: -- Installation completed successfully'
              priority: WARNING
              type: MULTIPLE
              manual_close: 'YES'
        -
          uuid: b1eea9e2cafa413888d9131eaf2d0d5f
          name: 'Event ID - 11724'
          type: ZABBIX_ACTIVE
          key: 'eventlog[Application,,,,11724,,skip]'
          delay: 10s
          history: 30d
          trends: '0'
          value_type: LOG
          tags:
            -
              tag: Windows
              value: 'Event ID alert'
          triggers:
            -
              uuid: a16ccb19fa05415196a745ea90f596ee
              expression: 'logeventid(/Microsoft Windows Application auditing/eventlog[Application,,,,11724,,skip])=1'
              name: 'Event ID11724_Product: -- Removal completed successfully.'
              priority: WARNING
              type: MULTIPLE
              manual_close: 'YES'
